FROM python:3.10

RUN apt-get update -y && \
    apt-get -y install git cmake sysstat

RUN git clone https://github.com/google/or-tools /or-tools

RUN cd /or-tools && \
    git fetch --all --tags --prune && \
    git checkout tags/v9.8 -b v9.8

WORKDIR /or-tools

RUN cmake -S . -B build -DBUILD_DEPS=ON && \
    cmake --build build --config Release --target all -j6 -v && \
    cmake --build build --config Release --target install -v && \
    mkdir -p /optimizer/build
